import Header from "@/layout/Navbar"
import "bootstrap/dist/css/bootstrap.rtl.min.css";
import "./globals.css";
import type { Metadata } from 'next'
import { getDictionary } from "@/get-dictionary";
import { Locale } from "@/i18n-config";


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: Locale }
}) {

  const dictionary: any = await getDictionary(params.lang)


  return (
    <html lang={params.lang} dir={params.lang === "ar" ? "rtl" : "ltr"} style={{ textAlign: params.lang === "ar" ? "right" : "left" }}>
      <body>
        <Header lang={params.lang} transaltes={dictionary} />
        {children}
      </body>
    </html>
  )
}
